### ISSUE TITLE
发现在iOS8中的bug

### ISSUE THREAD

**Issue by pangpingfei** [jonkykong/SideMenu#10]
在iOS8中，menuAddScreenEdgePanGesturesToPresent  设置左边手势，没效果，如果用menuAddPanGestureToPresent，则滑到右边缘再离开屏幕（或关闭的时候左滑到左边缘），会闪一下屏，具体表现为：快速关掉测滑页，然后马上再打开测滑页。

**Comment by jonkykong** [comment]
@pangpingfei Thank you for reporting this issue. This should be fixed in version 1.1.2. Please let me know if the problem continues.

**Comment by pangpingfei** [comment]
Thank you, I try the new version, it can work on iOS8 use "menuAddScreenEdgePanGesturesToPresent" function, but the bug I reported is still persist. Example: slide from left to the right edge, then leave.  Whether "menuAddPanGestureToPresent" or "menuAddScreenEdgePanGesturesToPresent".
(iOS8, 左边缘滑到右边缘再离开屏幕（或关闭的时候左滑到左边缘），会闪一下屏，具体表现为：快速关掉测滑页，然后马上再打开测滑页。)


In addition, seemingly you mistaked in the function "menuAddScreenEdgePanGesturesToPresent" .

"forMenu != .Right" & "forMenu != .Left" is reverse... please check it.

**Comment by jonkykong** [comment]
I'm having a difficult time reproducing the problem you're experiencing.
Does it only happen in iOS8? Does it happen in the example project on the
pod?

I'll make a fix for the swapped edges soon.

**Comment by pangpingfei** [comment]
@jonkykong 
My test environment: iphone 6,  iOS 8.1(12B411)
It happen in your example project.
I made a video of the screen. What's your email? I'll send you.

**Comment by jonkykong** [comment]
Jpkent@gmail.com

**Comment by jonkykong** [comment]
@pangpingfei I created a workaround for this issue by briefly setting the transition progress to 99.99% complete when it's at 100% complete when the gesture ends for iOS8 only. It appears to be resolved.

**Comment by pangpingfei** [comment]
@jonkykong Yeah, It appears to be resolved... Thank your very much!
