### ISSUE TITLE
non-animated dismissal results in black-screen

### ISSUE THREAD

**Issue by Skymax1986** [jonkykong/SideMenu#269]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

If you want to dismiss the menu, without an animation (eg: viewControllerForPresentedMenu?.dismiss(animated: false, completion: nil)) the dismissal results in a blackscreen. Is this behavior an oversight, or simply not supported, or is this a bug? 
It's easily reproducible with the demo-project if you change the dismissal in handleHideMenuTap to non-animated. 

It's not crucial for our usecase, but it did cost me an hour of debugging, so I wanted to ask if this is intended and why it does happen. 

btw: great project!

**Comment by jonkykong** [comment]
Fixed. 10197c53cfb29208b2e2c983bf193b954955849f

**Comment by iamchingel** [comment]
This problem still persists...I am getting a black screen when I do :
dismiss(animated : false)

**Comment by jonkykong** [comment]
@iamchingel I just verified this works as expected in the demo project.

**Comment by YuyaAbo** [comment]
I encountered same issue.

I avoided the issue. I set `SideMenuManager.menuAnimationDismissDuration` to 0.0, and `dismiss(animated: true)`.
```swift
// add function to class that YourViewController has SideMenu.
// UIApplication.shared.keyWindow?.rootViewController class is better.

// function that sets menuAnimationDismissDuration from the outside.
func setMenuAnimationDismissDuration(_ duration: Double) {
    SideMenuManager.menuAnimationDismissDuration = duration
}
```

```swift
/// ViewController in SideMenu
DispatchQueue.main.async { [weak self] in
    (UIApplication.shared.keyWindow?.rootViewController as? YourViewController)?.setMenuAnimationDismissDuration(0.0)
    self?.dismiss(animated: true) {
        (UIApplication.shared.keyWindow?.rootViewController as? YourViewController)?.setMenuAnimationDismissDuration(0.35) // 0.35 is default value
    }
}

**Comment by spacedema** [comment]
Have the same issue too. 

`transition.hideMenuStart().hideMenuComplete()` not executing if I call `dismiss(animated: false)`. 
But if I will correct the source code for this to be called, I still see an artifact on the screen while dismissing without animation.

**Comment by johndelong** [comment]
@jonkykong I was having a similar problem but figured out why. The reason your demo project works is because you've set the `sideMenuDelegate` and therefore your "Work-around" [here](https://github.com/jonkykong/SideMenu/commit/10197c53cfb29208b2e2c983bf193b954955849f ) does what you say it should.

For us however (and maybe others), we had no use for these delegate methods and therefore did not set the `sideMenuDelegate`. Although you say the implementation of the `sideMenuDelegate`  [is optional](https://github.com/jonkykong/SideMenu#uisidemenunavigationcontrollerdelegate), your work around requires you to set it in order for the fix to do its job. This could be where others are getting tripped up too.

Might be work adding a note to the README or call `transition.hideMenuStart().hideMenuComplete()` in a different spot?

**Comment by jonkykong** [comment]
This issue should now be resolved in version 6.0.0+ of SideMenu. Please run `pod update` and reopen this issue if the problem persists.
