### ISSUE TITLE
SideMenuNavigationController pushViewController infinite loop

### ISSUE THREAD

**Issue by garryzhong** [jonkykong/SideMenu#535]
when i launch my app, it crashes.

i use 6.2.6, show you my code.

![image](https://user-images.githubusercontent.com/5044230/64406188-c8513780-d0b3-11e9-88f6-af3c57bcaec3.png)

and show you my main thread backtrace

<img width="372" alt="WeChatcbaa8fe762f9dc7c176d24e5cb81fddd" src="https://user-images.githubusercontent.com/5044230/64406411-51686e80-d0b4-11e9-9157-044f1eafadb4.png">

**Comment by jonkykong** [comment]
Fixed in `6.2.7`.

**Comment by garryzhong** [comment]
i am trying with 6.2.7, but the problem still exists.
![image](https://user-images.githubusercontent.com/5044230/64413150-8b8d3c80-d0c3-11e9-8dd7-19a04f346d51.png)

**Comment by jonkykong** [comment]
What line is being called in the push coordinator?

**Comment by jonkykong** [comment]
`6.2.8`
